# Generated by Django 5.1.4 on 2024-12-24 02:12

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='아이디')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('full_name', models.CharField(max_length=150, verbose_name='이름')),
                ('phone_number', models.CharField(max_length=20, verbose_name='전화번호')),
                ('nationality', models.CharField(max_length=100, verbose_name='국적')),
                ('visa_type', models.CharField(choices=[('F4', 'F4 비자'), ('F2', 'F2 비자'), ('E7', 'E7 비자'), ('D10', 'D10 비자'), ('H2', 'H2 비자'), ('OTHER', '기타')], default='OTHER', max_length=10, verbose_name='비자 종류')),
                ('visa_expiry_date', models.DateField(blank=True, null=True, verbose_name='비자 만료일')),
                ('device', models.CharField(blank=True, max_length=200, verbose_name='디바이스')),
                ('terms_agreed', models.BooleanField(default=False, verbose_name='약관 동의')),
                ('oauth_type', models.CharField(blank=True, choices=[('GOOGLE', '구글'), ('KAKAO', '카카오'), ('NAVER', '네이버')], max_length=10, null=True, verbose_name='연동 타입')),
                ('oauth_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='연동 ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
