# Generated by Django 5.1.4 on 2024-12-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvisa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.URLField(blank=True, max_length=500, null=True)),
                ('image2', models.URLField(blank=True, max_length=500, null=True)),
                ('language', models.CharField(choices=[('KR', '한국어'), ('EN', '영어'), ('CN', '중국어'), ('VN', '베트남어')], max_length=2)),
                ('visa_type', models.CharField(choices=[('B1_C4', '여행비자 (B-1 ~ C-4)'), ('D2_D4', '유학생 (D-2 ~ D-4)'), ('D7_D9', '사업비자 (D-7 ~ D-9)'), ('D10', '회사구인 (D-10)'), ('E1_E7', '취업비자 (E-1 ~ E-7)'), ('E8_E9', '비전문취업 (E-8 ~ E-9)'), ('F1_F3', '동반가족 (F-1, F-3)'), ('F2', '거주 (F-2)'), ('F4', '재외동포 (F-4)'), ('F5', '영주자격 (F-5)'), ('F6', '국제결혼 (F-6)'), ('H2', '방문취업 (H-2)'), ('G1', '기타 (G-1)'), ('ETC', '그 밖에')], max_length=10)),
                ('post_type', models.CharField(choices=[('ROADMAP', '비자 로드맵'), ('BENEFIT', '혜택정보'), ('ADMIN', '비자/행정업무'), ('CHATBOT', '비자상담 챗봇'), ('AD', '광고'), ('NEWS', '한국소식')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('link', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='visa_type',
            field=models.CharField(choices=[('B1_C4', '여행비자 (B-1 ~ C-4)'), ('D2_D4', '유학생 (D-2 ~ D-4)'), ('D7_D9', '사업비자 (D-7 ~ D-9)'), ('D10', '회사구인 (D-10)'), ('E1_E7', '취업비자 (E-1 ~ E-7)'), ('E8_E9', '비전문취업 (E-8 ~ E-9)'), ('F1_F3', '동반가족 (F-1, F-3)'), ('F2', '거주 (F-2)'), ('F4', '재외동포 (F-4)'), ('F5', '영주자격 (F-5)'), ('F6', '국제결혼 (F-6)'), ('H2', '방문취업 (H-2)'), ('G1', '기타 (G-1)'), ('ETC', '그 밖에')], max_length=10, verbose_name='비자 종류'),
        ),
    ]
