# Generated by Django 5.1.4 on 2024-12-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvisa', '0004_post_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.TextField(max_length=500),
        ),
    ]
