# Generated by Django 5.1.4 on 2024-12-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvisa', '0005_alter_post_content_alter_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='show_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='show_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
