# Generated by Django 5.1.4 on 2025-01-01 14:46

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kvisa', '0006_post_show_end_date_post_show_main_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visa_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('B1_C4', '여행비자 (B-1 ~ C-4)'), ('D2_D4', '유학생 (D-2 ~ D-4)'), ('D7_D9', '사업비자 (D-7 ~ D-9)'), ('D10', '회사구인 (D-10)'), ('E1_E7', '취업비자 (E-1 ~ E-7)'), ('E8_E9', '비전문취업 (E-8 ~ E-9)'), ('F1_F3', '동반가족 (F-1, F-3)'), ('F2', '거주 (F-2)'), ('F4', '재외동포 (F-4)'), ('F5', '영주자격 (F-5)'), ('F6', '국제결혼 (F-6)'), ('H2', '방문취업 (H-2)'), ('G1', '기타 (G-1)'), ('ETC', '그 밖에')], max_length=100),
        ),
    ]
