# Generated by Django 5.1.4 on 2025-01-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvisa', '0007_alter_post_visa_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
